# Site settings
title: WEB-连接世界
description: leunggabou is a minimal yet powerful Jekyll theme for your blogs and websites.
cover: assets/images/img/home-bg.jpg
logo: assets/images/logo.png
favicon: assets/images/img/favicon.png
# baseurl: "/leunggabou/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://leunggabou.com" # the base hostname & protocol for your site
lean_cloud :
  app_id   :  h0VLBqXqt7BQzRvaRk9fUWBs-gzGzoHsz
  app_key  :  0n7pgyymgltq2x7m1k2p2Drx
# Social
facebook: facebook
twitter: twitter
github_username:    "Steven19960709"

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
anchorjs: true  
permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
# markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: "Steven19960709" #github username
repo: leunggabou #github repository
branch: master #branch
relative_source: ../leunggabou/ #source directory
destination: ../leunggabou/ #destination directory
production_url:  https://leunggabou.com/
source_url:  https://github.com/Steven19960709.comn #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml